version: 2.1
workflows:
  testing:
    jobs:
      - run-tests:
          context:
            - Default
jobs:
  run-tests:
    docker:
      - image: circleci/node:12.18.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: npm acces token stored in default context
          command: 'echo $npmAccessToken'
      - run:
          name: Install gulp globally
          command: 'sudo npm i -g gulp'
      - run:
          name: Install dependencies
          command: 'npm i'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: 'npm test'
