name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run linting
      run: npm run lint
    - name: Run unit tests
      run: npm run test
    - name: Run publishing in dry-run mode
      run: npm publish --dry-run
  versioncheck:
    name: Check version
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check if version has been updated
      id: versioncheck
      uses: EndBug/version-check@v2.1.1
      with:
        diff-search: true
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Version not updated
      if: steps.versioncheck.outputs.changed != 'true'
      run: 'echo "Version in package.json not updated:/" && exit 1'
    - name: Version updated
      run: 'echo Version in package.json updated'
